from dataclasses import dataclass

from koi_net.components import Cache
from koi_net.components.interfaces import HandlerType, KnowledgeHandler
from koi_net.protocol import EdgeProfile, EventType, KnowledgeObject
from rid_lib.ext import Bundle
from rid_lib.types import HTTPS, KoiNetEdge

from .space_manager import SpaceManager


@dataclass
class DGWriteHandler(KnowledgeHandler):
    cache: Cache
    space_manager: SpaceManager

    handler_type = HandlerType.Network
    rid_types = (KoiNetEdge,)

    def handle(self, kobj: KnowledgeObject):
        # don't process kobjs generated by this node
        if kobj.source is None:
            return

        if kobj.normalized_event_type not in (EventType.NEW, EventType.UPDATE):
            return

        # POST to DG API here
        client = self.space_manager.space_clients.get(kobj.source)
        if client:
            client.post_resource(kobj.contents)
